### ISSUE TITLE
lz4建议替换为lz4js前者本地安装失败

### ISSUE THREAD

**Issue by 2903710916** [innopals/node-sls-logger#1]

**Comment by bestmike007** [comment]
嗯，没想到这么快有人关注到这个项目。确实需要编译环境，考虑到性能的话更倾向于使用这个，如果是阿里云内网的话完全可以不使用压缩。我的想法是移除这个依赖，仅在配置了压缩选项的情况下再去加载，并且可以选择压缩的实现，不管是lz4还是lz4js都可以。

我会发布一个兼容的版本。

**Comment by bestmike007** [comment]
更新一下：lz4js压缩的结果推送到SLS报错：

```
{ errorCode: 'PostBodyUncompressError',
  errorMessage: 'post body uncompressed fail' }
```

**Comment by bestmike007** [comment]
发布了1.0.4版本到npm，现在直接使用了lz4里面的：[https://github.com/pierrec/node-lz4/blob/master/lib/binding.js](https://github.com/pierrec/node-lz4/blob/master/lib/binding.js)，不再需要build依赖关系。
